version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pwa_backend
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3360:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  mysql_data: